
framework:
    secret: '%env(APP_SECRET)%'
    session: true
    profiler: true

when@test:
    framework:
        test: true
        session:
            storage_factory_id: session.storage.factory.mock_file
